
package test;

import java.io.File;



public class myheader extends javax.swing.JPanel {

    private String username,  foto;
    
    public myheader() {
        initComponents();
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }
    
    public void refreshFoto(){
        
        File f = new File(this.foto); 
        f.toString();
        fotouser.setImage(new javax.swing.ImageIcon(getClass().getResource(f.toString())));
//        userName.setText(username);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fotouser = new test.ImageAvatar();
        userName = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        fotouser.setBorderSize(1);
        fotouser.setBorderSpace(1);
        fotouser.setImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/user1.png"))); // NOI18N
        fotouser.setPreferredSize(new java.awt.Dimension(150, 0));

        userName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        userName.setForeground(java.awt.Color.black);
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(userName, org.openide.util.NbBundle.getMessage(myheader.class, "myheader.userName.text")); // NOI18N
        userName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        nama.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nama.setForeground(java.awt.Color.darkGray);
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(nama, org.openide.util.NbBundle.getMessage(myheader.class, "myheader.nama.text")); // NOI18N
        nama.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(fotouser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(fotouser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private test.ImageAvatar fotouser;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
